apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: portal-front
  template:
    metadata:
      labels:
        app: portal-front
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: portal-front
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}   # Next.js actual port
