replicaCount: 1

image:
  repository: ghcr.io/hjsongggg/sailingstone-portal-front
  tag: latest
  pullPolicy: Always
  pullSecret: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  nodePort: null
