# 루트 values - ingress만 담당
namespace: cicd

ingress:
  enabled: true
  className: nginx
  host: portal.local

imagePullSecret:
  enabled: false
  name: ghcr-secret
  username: "hjsongggg"
  password: "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"
  email: "hjsong@sailingstone.io"

global:
  imagePullSecret:
    name: ghcr-secret
